
events{

}

http{
    upstream backend {
        server gateway1:3000;
        server gateway2:3000;
    }
    server{
        listen 80;
        location /{
            proxy_pass http://backend;
        }
    }
}